# Generated by Django 3.2.9 on 2021-12-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100)),
                ('staff_email', models.EmailField(max_length=254)),
                ('staff_phone', models.IntegerField()),
                ('designation', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='main/images')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
