# Generated by Django 3.2.9 on 2021-12-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211204_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
